### PR TITLE
fix: solves unable to run yarn command

### PR DESCRIPTION
**Pull request by andr9528**

### CODE REVIEW

**Review by LindvedKrvang — APPROVED** [review]
What happend in the yarn.lock? It flipped the places of all the `version` and `integrity`?

**Comment by LindvedKrvang** [comment]
Is there a Jira task for this or is it just a quick fix?

**Comment by andr9528** [comment]
> Is there a Jira task for this or is it just a quick fix?

No, it is just a quick fix. I tried to run yarn to get all the needed packaged, which errored out. Solved the issue together with Kryz, and we chose to make a quick PR with it, so others won't run into the same issue.

**Comment by andr9528** [comment]
> What happend in the yarn.lock? It flipped the places of all the `version` and `integrity`?

Not sure why it did that. Just ran `yarn`, after we had solved the issue. The actual file should be no different than before.

**Review by RasmusAlbrektsen — APPROVED** [review]

**Review by KvelaGorrrrnio — APPROVED** [review]

**Pull request merged**
